# Generated by Django 5.2.13 on 2026-05-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "machine_type",
                    models.CharField(
                        choices=[
                            ("roller", "Road Roller"),
                            ("excavator", "Excavator"),
                            ("vibrator", "Vibrator"),
                            ("hydraulic", "Hydraulic Machine"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="machines/"),
                ),
            ],
        ),
    ]
